name: Sonar merged
on:
  pull_request:
    types: 
      - closed
    branches:
      - main
  workflow_call:

jobs:
  runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo ${{ github.event.pull_request }}
          echo ${{ github.event_name }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm test