name: Sonar cloud on PR
on:
  push:
    branchs:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud-pull-request:
    if: github.event_name == 'pull_request' && ${{ !github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo ${{ github.event.pull_request.merged }}
          echo ${{ github.event_name }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm run test:ci
  sonarcloud-merged:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo event name ${{ github.event_name }}
          echo event action ${{ github.event.action }}
          echo github ref ${{ github.ref }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm test