name: Sonar cloud on PR
on:
  push:
    branchs:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud-pull-request:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo is merged ${{ github.event.pull_request.merged }}
          echo event name ${{ github.event_name }}
          echo event action ${{ github.event.action }}
          echo github ref ${{ github.ref }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git fetch --no-tags --depth=1 origin main
          git checkout -b main # create the main branch
          git checkout ${{ github.event.pull_request.head.sha }} # go back to the PR branch

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm run test:ci
  sonarcloud-merged:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo event name ${{ github.event_name }}
          echo event action ${{ github.event.action }}
          echo github ref ${{ github.ref }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm test